#spring.datasource.url=jdbc:mysql://localhost:3306/department_db
#spring.datasource.username=root
#spring.datasource.password=pass123
#
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update

spring:
  application:
    name: department-service
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: pass123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8000